### ISSUE TITLE
A fatal error is thrown when the BuddyPress plugin is deactivated

### ISSUE THREAD

**Issue by emaralive** [slaFFik/buddypress-groups-extras#146]
### Describe the bug
This condition (fatal error) was originally revealed when utilizing the **BP Beta Tester** plugin to upgrade **BuddyPress** (**BP**) to a **BP beta version** or downgrade a **BP beta version** to a **BP stable version**, e.g., **BP 11.4.0** to **BP 12.0.0-beta4** or **BP 12.0.0-beta4** to **BP 11.1.0**, however, the **BP Beta Tester plugin is not required to replicate a fatal error**,

### To Reproduce
**Steps to reproduce the behavior**:

There are 2 (two) scenarios that will invoke a fatal error, of which, each scenario indicates a different cause (source) for fault.

1. **Scenario 1**: **BP** and **Buddypress Groups Extras** (**BPGE**) plugins are **both** **deactivated** and then **BPGE is activated**.
2. **Scenario 2**: **BP** and **BPGE** are **both activated** and then **BP is deactivated**. -- **Note**: **This is the scenario when utilizing the BP Beta Tester plugin**.

**Scenario 1:**
The following screenshot is indicative of the fault as viewed from the "**Install Plugins**" (**site.url/wp-admin/plugins.php**) page:

![screenshot-win10-me-2023 11 20-04_42_58](https://github.com/slaFFik/buddypress-groups-extras/assets/50045193/02ac0506-d9f2-4655-ac92-b29f1260aac1)

**WordPress** (**WP**) catches the **fatal error** and prevents **BPGE** from being activated. The **cause** (**source**) is an undefined **WP** function **`add_blog_option`** that was called on **line 109** of the **bgpe.php** file.

**Scenario 2:**
This is more fatalistic in which the recovery is via the "**Recovery Mode**" process, of which the following screenshot provides example of such:

![screenshot-win10-me-2023 11 20-04_57_52](https://github.com/slaFFik/buddypress-groups-extras/assets/50045193/9928aed0-67f0-4e59-a6e0-2c7013e7d5f7)

This next screenshot is after logging into "**Recovery Mode**" via the link provided by the sent email:

![screenshot-win10-me-2023 11 20-05_02_22](https://github.com/slaFFik/buddypress-groups-extras/assets/50045193/f68514bb-c4a0-4da1-a7df-9c24a2b6f76e)

The **cause** (**source**) is now an undefined **BP** function **`bp_is_active`** that was called on **line 257** of the **bpge.php** file. This next screenshot represents the "**Plugins screen**":

![screenshot-win10-me-2023 11 20-05_07_14](https://github.com/slaFFik/buddypress-groups-extras/assets/50045193/6e6bb115-49d6-4564-8b0b-586d14682c21)

The **recovery** is to **deactivate BPGE** and exit the "**Recovery Mode**". Another course of action could have been to **activate BP**. Neither here nor there, **Scenarios 1 & 2** represent **undesirable** events.

### Expected behavior
This next screenshot is what should have happened and from what I can tell was the original intent that would have avoided the conditions for fatal error:

![screenshot-win10-me-2023 11 20-06_20_06](https://github.com/slaFFik/buddypress-groups-extras/assets/50045193/6f58fdce-5f8a-4c95-9cf7-f31213ccc10a)

**Note: A patch was created and applied to achieve the expected behavior**.

### Additional context
I have what I call an **initial patch** that I could submit as a PR, however, it only addresses the "**fatal error**" conditions and corrections for **PHPCS** compliance with the exception of 3 database oriented warnings in regard to potential caching issues within the function **`bpge_clear`** (related to **PR Clean post cache after field save.**  **#103** and Issue **Investigate possibility to switch to wp_update_post()** **#104**), of which can be resolved at a different time. 

Another observation is version control, the header for **bpge.php** indicates on **line 8** that the version is **3.6.10** and **line 18** of **same file** has **`define( 'BPGE_VERSION', '3.6.9.1' );`**, of which I'm finding a bit confusing due to the contradiction, maybe you could shed some light on this contradiction.

**Comment by slaFFik** [comment]
Thank you very much for the details bug report!
